name: fake_store_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  shimmer: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  image_picker: ^1.1.2
  dio: ^5.0.0
  file_picker: ^10.2.0
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/LOGO.png


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/LOGO.png
  #branding: assets/icon/LOGO.png
  android: true
  ios: true
  web: false
  android_gravity: center





